#!/bin/bash

ParseArgument() {
    # check if --remove flag is active. Default mode is install.
    case "$1" in
    "-r" | "--remove")
        mode="remove"
        ;;
    "")
        ##set the default mode to install
        mode="install"
        ;;
    "-i" | "--install")
        mode="install"
        ;;
    *)
        echo "Wrong argument '$1'"
        echo "Usage;"
        echo "-i or --install for installing packages. The default mode is install."
        echo "-r or --remove for removing packges."
        exit 1
        ;;
    esac
}

# Detecting package manager.
DetectPM() {
    #PACMAN support
    if command -v pacman >/dev/null 2>&1; then
        packageManager="pacman"

        #-Rns removes packages with it's dependencies.
        removeCommand="sudo pacman -Rns"
        installCommand="sudo pacman -S"

        if [[ "$mode" == "remove" ]]; then
            ## list installed packages installed on local machine.
            list="pacman -Qq"
            ## show preview of installed package
            preview="pacman -Qi {}"
        else
            ## list pacman repository
            list="pacman -Ssq"
            operation="sudo pacman -S"
            preview="pacman -Si {}"
        fi

    #APT support
    elif command -v apt >/dev/null 2>&1; then
        packageManager="apt"
        removeCommand="sudo apt-get remove"
        installCommand="sudo apt-get install"

        if [[ "$mode" == "remove" ]]; then
            ## list only installed programs.
            list="dpkg-query -W -f='\${Package}\n'"
            preview="dpkg -s {} 2>/dev/null"
        else
            list="apt-cache pkgnames"
            preview="apt-cache show {}"
        fi

    #Brew suppport
    elif command -v brew >/dev/null 2>&1; then
        packageManager="brew"
        removeCommand="brew uninstall"
        installCommand="brew install"

        if [[ "$mode" == "remove" ]]; then
            list="brew list -1"
            preview="brew info {}"
        else
            list="{ brew formulae; brew casks; }"
            preview="brew info {}"
        fi

    #DNF support
    elif command -v dnf >/dev/null 2>&1; then
        packageManager="dnf"
        removeCommand="sudo dnf remove"
        installCommand="sudo dnf install"

        if [[ "$mode" == "remove" ]]; then
            list="dnf -q list installed | tail -n +2 | awk '{print \$1}'"
            preview="dnf info {}"
        else
            list="dnf -q list available | tail -n +2 | awk '{print \$1}'"
            preview="dnf info {}"
        fi

    #ZYPPER suppport
    elif command -v zypper >/dev/null 2>&1; then
        packageManager="zypper"
        removeCommand="sudo zypper remove"
        installCommand="sudo zypper install"

        if [[ "$mode" == "remove" ]]; then
            list="zypper -q search -i | tail -n +5 | awk -F'|' '{print \$2}' | tr -d ' '"
            preview="zypper info {}"
        else
            list="zypper -q search | tail -n +5 | awk -F'|' '{print \$2}' | tr -d ' '"
            preview="zypper info {}"
        fi

    #Exit if no package manager found.
    else
        echo "No supported package manager found."
        exit 1
    fi

    if [[ "$mode" == "remove" ]]; then
        operation="$removeCommand"
    else
        operation="$installCommand"
    fi

}

CheckFzf() {
    #Check if fzf is installed.
    if ! command -v fzf >/dev/null 2>&1; then
        echo "fzf is not installed."

        #ask to user if they want to install fzf.
        read -r -p "Do you want to install fzf using $packageManager? (y/N): " fzfAns

        if [[ "$fzfAns" == "y" || "$fzfAns" == "Y" ]]; then
            echo "installing fzf..."
            eval "$installCommand fzf"

            #check if fzf installation complete
            if ! command -v fzf >/dev/null 2>&1; then
                echo "fzf installation failed. Please re-run the script or install it manually."
                exit 1
            else
                echo "fzf installation complete."
            fi
        else
            echo "Can not run the script without fzf. Exiting."
            exit 1
        fi
    fi
}

HandleAur() {
    if command -v yay >/dev/null 2>&1; then
        aurHelper="yay"
    elif command -v paru >/dev/null 2>&1; then
        aurHelper="paru"
    else
        echo "No AUR helper found. Exiting."
        exit 0
    fi

    read -r -p "Do you wish to search  using $aurHelper? (y/N): " aurAns
    if [[ "$aurAns" == "y" || "$aurAns" == "Y" ]]; then
        echo "Listing AUR packages."
        aurSelected=$(eval "$aurHelper -Slq" | fzf -m --prompt="AUR")

        if [[ -n "$aurSelected" ]]; then
            packages=$(echo "$aurSelected" | tr '\n' ' ')
            echo "$packages will be installed using $aurHelper."
            eval "$aurHelper -S $packages"
        else
            echo "No package selected. Exiting."
        fi
    else
        echo "No package selected. Exiting."
    fi
}

Run() {
    local prompt selectedPackages packages
    prompt=$(tr '[:lower:]' '[:upper:]' <<<"${mode:0:1}")${mode:1}
    selectedPackages=$(eval "$list" | fzf -m --preview="$preview" --preview-window=top:50%:wrap --prompt="$prompt ($packageManager)> ")

    if [[ -n "$selectedPackages" ]]; then
        packages=$(echo "$selectedPackages" | tr '\n' ' ')
        echo "$prompt $packages"
        eval "$operation $packages"
    else
        if [[ $packageManager == "pacman" && $mode == "install" ]]; then
            HandleAur
        else
            echo "No package selected, Exiting."
        fi
    fi
}

main() {
    ParseArgument "$@"
    DetectPM
    CheckFzf
    Run
}

main "$@"
